# Generated by Django 3.2.1 on 2021-08-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='review',
            new_name='cus_review',
        ),
    ]
