# Generated by Django 3.2.1 on 2021-08-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0002_rename_review_cus_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=80)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_website', models.CharField(max_length=80)),
                ('business_phone', models.CharField(max_length=80)),
            ],
        ),
    ]
