# Generated by Django 3.2.1 on 2021-08-04 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
