# Generated by Django 3.2.1 on 2021-08-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_delete_listing'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cus_review',
            table='Cus_review',
        ),
    ]
