# Generated by Django 3.2.1 on 2021-08-04 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customerapp', '0005_alter_cus_review_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cus_review',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cus_review',
            name='name',
        ),
        migrations.AddField(
            model_name='cus_review',
            name='star',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='cus_review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
