# Generated by Django 3.2.1 on 2021-08-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0008_auto_20210809_1824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
