# Generated by Django 3.2.1 on 2021-07-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0003_auto_20210726_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
