# Generated by Django 3.2.1 on 2021-07-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0004_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='kidsproduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='images')),
                ('specification', models.TextField(null=True)),
            ],
        ),
    ]
