# Generated by Django 3.2.1 on 2021-08-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0006_auto_20210728_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='product1',
            name='specification',
            field=models.TextField(null=True),
        ),
    ]
