# Generated by Django 3.2.1 on 2021-08-12 10:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productsapp', '0008_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_address',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing_address',
            name='user',
            field=models.ForeignKey(default=datetime.datetime(2021, 8, 12, 10, 37, 40, 151338, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('py', 'Paypal'), ('cp', 'Check Payment'), ('dbt', 'Direct Bank Transfer'), ('ct', 'Cash on Delivery')], max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
