# Generated by Django 3.2.1 on 2021-08-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0009_auto_20210812_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_address',
            name='date',
        ),
    ]
