# Generated by Django 3.2.1 on 2021-08-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0010_remove_billing_address_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
