# Generated by Django 3.2.1 on 2021-08-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0013_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='billing_address',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
    ]
